#!/bin/bash
exec 2>&1
source /env
source /etc/profile.d/rvm.sh
cd /var/www/arvados-api/current
echo "Starting puma in $(pwd)"
exec chpst -u www-data:www-data -e "/env.puma" \
      bundle exec puma -t 0:512 -e production -b tcp://0.0.0.0:8100
